### ISSUE TITLE
[Bug]: Failed to start rabbitmq.service: Unit rabbitmq.service not found

### ISSUE THREAD

**Issue by Erbsensuppee** [pantos-io/servicenode#3]
### Contact Details

etsch.work@sbg.at

### Problem:
During the installation process outlined below, we encountered the following error:

```
Failed to start rabbitmq.service: Unit rabbitmq.service not found
```

### System Information:
- No LSB modules are available.
- Distributor ID: Debian
- Description: Debian GNU/Linux 12 (bookworm)
- Release: 12
- Codename: bookworm
- Kernel Version: Linux pantosPi 6.6.28+rpt-rpi-v8 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

### Installation Steps:
```bash
curl -s --compressed "https://pantos-io.github.io/servicenode/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/servicenode.gpg >/dev/null
sudo curl -s --compressed -o /etc/apt/sources.list.d/pantos-servicenode.list "https://pantos-io.github.io/servicenode/pantos-servicenode.list"
sudo apt update
sudo apt install pantos-service-node
```

### Observations:
After the installation, it became apparent that no new user had been created for RabbitMQ.

### Verification Steps:
To verify the absence of a new user, the following commands were executed:

```bash
sudo rabbitmqctl list_users
sudo rabbitmqctl list_vhosts
```

### Quick Fix:
To address this issue promptly, we propose the following steps:

```bash
sudo rabbitmqctl add_user pantos-service-node <PASSWORD>
sudo rabbitmqctl add_vhost pantos-service-node
sudo rabbitmqctl set_permissions -p pantos-service-node pantos-service-node ".*" ".*" ".*"
```

### Installation Type

Debian Package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danut13** [comment]
Hi @Erbsensuppee,
Can you please provide the installation logs?

**Comment by Erbsensuppee** [comment]
Hello @danut13,
I tried to recreate the issue on a fresh system.
The error message did not appear in that log, but the RabbitMq user and vhost was not created.
[term.log](https://github.com/pantos-io/servicenode/files/15162068/term.log)
```
pantos@pantosPi:~ $ sudo rabbitmqctl list_users
Listing users ...
user	tags
guest	[administrator]
pantos@pantosPi:~ $ sudo rabbitmqctl list_vhosts
Listing vhosts ...
name
/
```

**Comment by juanmanuel-tirado** [comment]
#79 should fix this issue.
