### ISSUE TITLE
[Bug]: Issue with fresh installation of pantos-service-node v1.6 on Raspberry Pi

### ISSUE THREAD

**Issue by Erbsensuppee** [pantos-io/servicenode#4]
### Contact Details

etsch.work@sbg.at

## Problem:
After completing the installation process, the expected 'service-node-signer.pem' file is not generated.

## System Information:
- No LSB modules are available.
- Distributor ID: Debian
- Description: Debian GNU/Linux 12 (bookworm)
- Release: 12
- Codename: bookworm
- Kernel Version: Linux pantosPi 6.6.28+rpt-rpi-v8 SMP PREEMPT Debian 1:6.6.28-1+rpt1 (2024-04-22) aarch64 GNU/Linux

## Installation Steps to Recreate the Bug:
1. Execute the following commands:
```bash
curl -s --compressed "https://pantos-io.github.io/servicenode/KEY.gpg" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/servicenode.gpg >/dev/null
sudo curl -s --compressed -o /etc/apt/sources.list.d/pantos-servicenode.list "https://pantos-io.github.io/servicenode/pantos-servicenode.list"
sudo apt update
sudo apt install pantos-service-node
```
## Observations:
Upon completion of the installation process, the 'service-node-signer.pem' file is not generated in the expected location.

## Verifications Steps:
```bash
ls -la /etc/pantos | grep service-node-signer.pem
```
#### Screenshot to prove that on the hole system there is no service-node-signer.pem file
![Screenshot from 2024-05-13 13-53-39](https://github.com/pantos-io/servicenode/assets/119676896/8ccf1aec-1145-417d-a0e7-61ec2e60ae66)

## Apt log Files:
[term.log](https://github.com/pantos-io/servicenode/files/15294035/term.log)

## Quick fix Solution:
Utilize the following script to generate the missing file:
https://github.com/pantos-io/common/blob/main/scripts/generate-signer-key.py

## Problem Description:
I have identified an issue related to the signer key in the file `/servicenode/linux/debian/postinst`.

**Code Snippet (Problem):**
```bash
# Signer key
if [ ! -e "${signer_key_file}" || -z "$SIGNER_KEY_PASSWORD" ]; then
    if [ ! command -v ssh-keygen ]; then
        echo "ssh-keygen is not installed, please install the package with the recommended dependencies to generate the key"
        exit 1
    fi
    echo "Signer key does not exist, generating new one"
    read -s -p "Please enter your password for your PEM file: " passwd
    ssh-keygen -t ed25519 -f "$signer_key_file" -N "$passwd" >/dev/null 2>&1
    echo "SIGNER_KEY_PASSWORD='$passwd'" >> ${env_file}
fi
```

## Proposed Solution:
```bash
# Check if the signer key file doesn't exist or SIGNER_KEY_PASSWORD is empty
if [ ! -e "${signer_key_file}" ] || [ -z "$SIGNER_KEY_PASSWORD" ]; then
    # Check if ssh-keygen is installed
    if ! command -v ssh-keygen &>/dev/null; then
        echo "ssh-keygen is not installed. Please install the package with the recommended dependencies to generate the key."
        exit 1
    fi

    echo "Signer key does not exist; generating a new one"
    read -s -p "Please enter your password for your PEM file: " passwd
    ssh-keygen -t ed25519 -f "$signer_key_file" -N "$passwd" >/dev/null 2>&1
    echo "SIGNER_KEY_PASSWORD='$passwd'" >> "${env_file}"
fi
```

### Installation Type

Debian Package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by danut13** [comment]
Hi @Erbsensuppee, thanks for pointing it out. We will include the fix in the next release
